# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x06signal\"U\n\rSignalRequest\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.signal.RequestType\x12\x10\n\x08\x66unction\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"7\n\tSignalAck\x12\x1c\n\x03\x61\x63k\x18\x01 \x01(\x0e\x32\x0f.signal.AckType\x12\x0c\n\x04resp\x18\x02 \x01(\x05*h\n\x0bRequestType\x12\x14\n\x10\x45xecuteAfterLoad\x10\x00\x12\x0b\n\x07\x45xecute\x10\x01\x12\x08\n\x04Load\x10\x02\x12\n\n\x06Unload\x10\x03\x12\x14\n\x10\x45xecuteForRecord\x10\n\x12\n\n\x06Replay\x10\x0b*\x1e\n\x07\x41\x63kType\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07Inavail\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTTYPE']._serialized_start=168
  _globals['_REQUESTTYPE']._serialized_end=272
  _globals['_ACKTYPE']._serialized_start=274
  _globals['_ACKTYPE']._serialized_end=304
  _globals['_SIGNALREQUEST']._serialized_start=24
  _globals['_SIGNALREQUEST']._serialized_end=109
  _globals['_SIGNALACK']._serialized_start=111
  _globals['_SIGNALACK']._serialized_end=166
# @@protoc_insertion_point(module_scope)
